version: '3.8'

services:
  # Django Producer (my_first_ci_project) - DEVELOPMENT VERSION
  producer:
    build: ./my_first_ci_project
    ports:
      - "8000:8000"    # Django REST API
      - "8765:8765"    # WebSocket server
    volumes:
      - ./my_first_ci_project:/app  # Hot reload - code from host
    environment:
      - MONGO_DB=my_first_ci_db
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password
      - DEBUG=1  # Development mode - auto-reload enabled
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      - mongo
    networks:
      - app-network

  # WebSocket Consumer (my_first_consumer) - DEVELOPMENT VERSION
  consumer:
    build: ./my_first_consumer
    volumes:
      - ./my_first_consumer:/app  # Hot reload - code from host
    environment:
      - WEBSOCKET_URL=ws://producer:8765
      - API_URL=http://producer:8000/api
    depends_on:
      - producer
    networks:
      - app-network
    stdin_open: true
    tty: true

  # MongoDB Database
  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: my_first_ci_db
    volumes:
      - mongo_data:/data/db
      - ./my_first_ci_project/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network

  # Optional: MongoDB Express (Web UI for MongoDB)
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: 