name: CI-CD Chapter-CI

on:
  pull_request:
    branches: [ "master" ]  # Se ejecuta en pull requests hacia master
    paths:
      - 'Chapter-CI/**'  # Solo se ejecuta cuando hay cambios en Chapter-CI
jobs:
  print-hash:
    runs-on: ubuntu-latest    
    steps:
    - name: Print commit hash
      run: |
        echo "Commit Hash on PR: ${{ github.sha }}"
        echo "Short Hash on PR: ${GITHUB_SHA:0:7}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit Message: ${{ github.event.head_commit.message }}"
        
  ci-cd: 
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3         
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install django
        pip install pytest-cov
        pip install mongoengine
        pip install djangorestframework
        if [ -f Chapter-CI/my_first_ci_project/requirements.txt ]; then pip install -r Chapter-CI/my_first_ci_project/requirements.txt; fi
        
    - name: Run Django tests
      run: |
        cd Chapter-CI/my_first_ci_project
        python manage.py test

    - name: Run coverage
      run: |
        cd Chapter-CI/my_first_ci_project
        coverage run manage.py test
        coverage report --fail-under=95
        
  validate-env:
    runs-on: ubuntu-latest    
    env: master
    steps:
    - shell: bash
      env:
        MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      run: |
        echo $MONGO_USERNAME 
        echo $MONGO_PASSWORD


