name: Print Fake Deploy APP Chapter-CI
 
on:
  push:
    branches: [ "master" ]  # Se ejecuta solo en push a master
    paths:
      - 'Chapter-CI/**'  # Solo se ejecuta cuando hay cambios en Chapter-CI

jobs:
  print-hash:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Print Deploy 
      run: |
        echo "Deploy to production....."
        
