name: Print Commit Hash

on:
  push:
    branches: [ "master" ]  # Se ejecuta solo en push a master
    paths:
      - 'Chapter-CI/**'  # Solo se ejecuta cuando hay cambios en Chapter-CI

jobs:
  print-hash:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Print commit hash
      run: |
        echo "Commit Hash: ${{ github.sha }}"
        echo "Short Hash: ${GITHUB_SHA:0:7}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit Message: ${{ github.event.head_commit.message }}"
      